"""add push_subscriptions table

Revision ID: 3f8b0dd19a92
Revises: e686b0d7660a
Create Date: 2026-09-16 08:46:57.737467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8b0dd19a92'
down_revision: Union[str, Sequence[str], None] = 'e686b0d7660a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('previous_section', sa.String(), nullable=True),
    sa.Column('new_section', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_history_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_history_id'))

    op.drop_table('section_history')
    # ### end Alembic commands ###
