"""banque de questions modifiable, niveau auto

Revision ID: 7b43f0d5ba18
Revises: bfdb8520e38b
Create Date: 2026-09-09 08:56:45.094024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b43f0d5ba18'
down_revision: Union[str, Sequence[str], None] = 'bfdb8520e38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
