"""add is_super_admin to users

Revision ID: c90b17d7b816
Revises: 52bc4107e892
Create Date: 2026-09-04 10:24:23.500161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90b17d7b816'
down_revision: Union[str, Sequence[str], None] = '52bc4107e892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', sa.String(), nullable=True))

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('room_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'status',
            sa.Enum('PENDING', 'APPROVED', name='membershipstatus'),
            nullable=False,
            server_default='APPROVED'
        ))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('room_memberships', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###