"""add reply_to_id

Revision ID: e686b0d7660a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-14 19:20:40.672173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e686b0d7660a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('section', sa.Enum('DEBATE', 'INTERPRETATION', 'NEWS', 'DRAMA', name='section'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_id'), ['id'], unique=False)

    op.create_table('level_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('suggested_level', sa.String(), nullable=False),
    sa.Column('final_level', sa.String(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('level_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_assessments_id'), ['id'], unique=False)

    op.create_table('section_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('previous_section', sa.String(), nullable=True),
    sa.Column('new_section', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_history_id'), ['id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'messages', ['reply_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('section_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_history_id'))

    op.drop_table('section_history')
    with op.batch_alter_table('level_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_assessments_id'))

    op.drop_table('level_assessments')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_id'))

    op.drop_table('assessment_questions')
    # ### end Alembic commands ###
